backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:

  - name: "novel"
    label: "Daftar Novel"
    folder: "content/novel"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul Novel", name: "title", widget: "string" }
      - { label: "Cover Novel", name: "cover", widget: "image" }
      - { label: "Penulis Asli", name: "author", widget: "string" }
      - { label: "Sinopsis", name: "synopsis", widget: "text" }

  
  - name: "posts"
    label: "Chapter"
    folder: "post"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul Bab (misal: Bab 1 - Awal Cerita)", name: "title", widget: "string" }
      - { label: "Pilih Novel", name: "novel", widget: "string", hint: "Ketik judul novelnya" }
      - { label: "Isi Terjemahan Bab", name: "body", widget: "markdown" }